#!/bin/bash
source ./.linamps/lib/@all.sh

include_all_config

# Push config files into the container
incus file push config/sites/nginx.conf \
    "$CONTAINER_NAME/etc/nginx/nginx.conf"
incus file push config/sites/setup.conf \
    "$CONTAINER_NAME/etc/nginx/http.d/default.conf"

# Reload Nginx gracefully (soft reload)
incus exec "$CONTAINER_NAME" -- bash -c "nginx -s reload"
